apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-app
  namespace: sample-web-app-01
  labels:
    app: sample-web-app-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-web-app-01
  template:
    metadata:
      labels:
        app: sample-web-app-01
    spec:
      containers:
      - name: sample-web-app-01
        image: codefirst.azurecr.io/samplek8swebapp:0.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      imagePullSecrets:
      - name: codefirstreg

---

apiVersion: v1
kind: Service
metadata:
  name: sample-web-app-01
  namespace: sample-web-app-01
spec:
  type: NodePort
  selector:
    app: sample-web-app-01
  ports:
  - protocol: TCP
    port: 30001
    targetPort: 8080
    nodePort: 30001